# Generated by Django 5.1.6 on 2025-03-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genre_id", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("movies", models.ManyToManyField(to="movie.movie")),
            ],
        ),
    ]
