# Generated by Django 5.1.6 on 2025-03-11 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("genre", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genre",
            name="genre_id",
        ),
    ]
