# Generated by Django 5.1.6 on 2025-03-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("image_url", models.CharField(max_length=255)),
                ("avg_rating", models.FloatField()),
            ],
        ),
    ]
