# Generated by Django 5.1.6 on 2025-02-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(choices=[('Coseno', 'Coseno'), ('Pearson', 'Pearson')], max_length=32)),
                ('tipo', models.CharField(choices=[('Usuario-Usuario', 'Usuario-Usuario'), ('Item-Item', 'Item-Item')], max_length=32)),
                ('k', models.PositiveIntegerField()),
            ],
        ),
    ]
