# Generated by Django 5.1.6 on 2025-03-11 00:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0001_initial"),
        ("movie_rating", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="movierating",
            unique_together={("user", "movie")},
        ),
        migrations.AlterField(
            model_name="movierating",
            name="rating",
            field=models.FloatField(),
        ),
    ]
